apiVersion: apps/v1
kind: Deployment
metadata:
  name: hash-app-dep
  namespace: hash-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hash-app
  template:
    metadata:
      labels:
        app: hash-app
    spec:
      imagePullSecrets:
        - name: docker-reqistry-secret
      containers:
        - name: request-counter
          image: ilikka/pingpong_app:004
          imagePullPolicy: Always
          env:
            - name: FLASK_PORT
              value: '5000'
        - name: log-output-app
          image: ilikka/logoutput_app:004
          imagePullPolicy: Always
          env:
            - name: BACKEND_URL 
              value: http://hash-app-svc:5000/ping
