FROM python:3.10-slim

WORKDIR /app
# Copy the Python script into the container
COPY hash.py  .
# Install any necessary dependencies (though none are required for this app)

# Command to run the Python script when the container starts
CMD ["python", "hash.py"]