apiVersion: v1
kind: Service
metadata:
  name: postgres-service-svc
  namespace: todos-ns
  labels:
    app: postgres-db
spec:
  selector: 
    app: postgres-db
  ports:
    - port: 5432
      targetPort: 5432
      name: possu-db

