apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: todos-ns
spec:
  serviceName: postgres-service
  replicas: 1  # Adjust based on need
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: todos
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
            - name: init-script 
              mountPath: /docker-entrypoint-initdb.d/init-db.sql
              subPath: init-db.sql
      volumes: 
        - name: init-script
          configMap:
            name: postgres-init-script
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 10Mi  # Adjust size as needed
