apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: devops-ns
data:
  init-db.sql: |
    CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
    );
    DO $$ 
    BEGIN
        -- Create sequence if it doesn't exist
        IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE schemaname = 'public' AND sequencename = 'select_counter_seq') THEN
            CREATE SEQUENCE select_counter_seq START 1;
        END IF;

    END $$;

