# Use the official Python image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the app files to the container
COPY todo_app.py .

COPY requirements.txt . 
RUN pip install  -r requirements.txt 


# Expose the port that Flask uses
EXPOSE 3000

# Run the app
CMD ["python", "todo_app.py"]
