# Use the official Python image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the app files to the container
COPY todo_backend.py .

COPY requirements.txt . 
RUN pip install  -r requirements.txt 



# ENV FLASK_HOST=0.0.0.0
#ENV FLASK_PORT=3000
# ENV PING_PATH=/pingpong

# ENV FILE_DIRECTORY=./
# ENV FILE_NAME=outs.txt
# Expose the port that Flask uses
EXPOSE 5005

# Run the app
CMD ["python", "todo_backend.py"]
