apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todos-volume-claim # name of the volume claim, this will be used in the deployment
  namespace: todos-namespace
spec:
  storageClassName: my-example-pv # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
