# Use the official Python image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the app files to the container
COPY logoutput_app.py .
COPY requirements.txt . 


# Install Flask
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose the port that Flask uses
EXPOSE 3000

# Run the app
CMD ["python", "logoutput_app.py"]
   